### ISSUE TITLE
ImportPageStream() panics randomly (1/1000 chance)

### ISSUE THREAD

**Issue by hsluoyz** [signintech/gopdf#166]
ImportPageStream() function panics randomly with a very low chance (1/1000). Do we know if there is any undelying bugs in it? At least can we return error instead of crashing?

Panic:

```
panic: Failed to get page resources: Page 8 does not exist!! [recovered]
	panic: Failed to get page resources: Page 8 does not exist!!
```

```go
func (this *Importer) ImportPage(pageno int, box string) int {
	// If page has already been imported, return existing tplN
	pageNameNumber := fmt.Sprintf("%s-%04d", this.sourceFile, pageno)
	if _, ok := this.importedPages[pageNameNumber]; ok {
		return this.importedPages[pageNameNumber]
	}

	res, err := this.GetWriter().ImportPage(this.GetReader(), pageno, box)
	if err != nil {
		panic(err)  // <----------------------------- crash
	}

	// Get current template id
	tplN := this.tplN

	// Set tpl info
	this.tplMap[tplN] = &TplInfo{SourceFile: this.sourceFile, TemplateId: res, Writer: this.GetWriter()}

	// Increment template id
	this.tplN++

	// Cache imported page tplN
	this.importedPages[pageNameNumber] = tplN

	return tplN
}
```

```go
// ImportPageStream imports page using a stream.
// Return template id after importing.
// gofpdi code
func (gp *GoPdf) ImportPageStream(sourceStream *io.ReadSeeker, pageno int, box string) int {
	// Set source file for fpdi
	gp.fpdi.SetSourceStream(sourceStream)

	// gofpdi needs to know where to start the object id at.
	// By default, it starts at 1, but gopdf adds a few objects initially.
	startObjID := gp.GetNextObjectID()

	// Set gofpdi next object ID to  whatever the value of startObjID is
	gp.fpdi.SetNextObjectID(startObjID)

	// Import page
	tpl := gp.fpdi.ImportPage(pageno, box) // <---------------------- into this

	// Import objects into current pdf document
	tplObjIDs := gp.fpdi.PutFormXobjects()

	// Set template names and ids in gopdf
	gp.ImportTemplates(tplObjIDs)

	// Get a map[int]string of the imported objects.
	// The map keys will be the ID of each object.
	imported := gp.fpdi.GetImportedObjects()

	// Import gofpdi objects into gopdf, starting at whatever the value of startObjID is
	gp.ImportObjects(imported, startObjID)

	// Return template ID
	return tpl
}
```

**Comment by akgitcom** [comment]
metoo...
`panic: Failed to get page resources: Page 9 does not exist!!

goroutine 1 [running]:
github.com/phpdave11/gofpdi.(*Importer).ImportPage(0xc0002a2000, 0x9, 0x7a5e1a, 0x9, 0xc00327a498)
        G:/golang/pkg/mod/github.com/phpdave11/gofpdi@v1.0.11/importer.go:124 +0x36d
github.com/signintech/gopdf.(*GoPdf).ImportPage(0xc000080f00, 0xc000210080, 0x1c, 0x9, 0x7a5e1a, 0x9, 0x0)
        G:/golang/pkg/mod/github.com/signintech/gopdf@v0.9.17/gopdf.go:882 +0xf4
main.main()
        G:/golang/pdfwater/main.go:123 +0xf04`
