### ISSUE TITLE
Crash in pdf.AddTTFFont with Roboto-Regular.ttf font file

### ISSUE THREAD

**Issue by remusmp** [signintech/gopdf#245]
Hello,

I am getting a crash when doing `pdf.AddTTFFont` with `Roboto-Regular.ttf` from `https://fonts.google.com/specimen/Roboto`.

Here is my go code:
```
pdf := gopdf.GoPdf{}
err := pdf.AddTTFFont("roboto", "roboto-regular.ttf")
if err != nil {
http.Error(w, "font not found", http.StatusInternalServerError)
return
}
err = pdf.SetFont("roboto", "", 16)
if err != nil {
http.Error(w, "failed to set font", http.StatusInternalServerError)
return
}
pdf.Start(gopdf.Config{ PageSize: *gopdf.PageSizeA4 })  
pdf.AddPage()
```

And here is the crash from logs:
```
squad-rest-api  | 2023/02/04 18:06:59 http: panic serving 172.18.0.4:43364: interface conversion: gopdf.IObj is *gopdf.UnicodeMap, not *gopdf.ProcSetObj
squad-rest-api  | goroutine 13 [running]:
squad-rest-api  | net/http.(*conn).serve.func1()
squad-rest-api  | 	/usr/local/go/src/net/http/server.go:1854 +0xbf
squad-rest-api  | panic({0xa820e0, 0xc000e28ab0})
squad-rest-api  | 	/usr/local/go/src/runtime/panic.go:890 +0x263
squad-rest-api  | github.com/signintech/gopdf.(*GoPdf).setSubsetFontObject(0xc00018af00, 0xc0002a2240, {0xb3d4be, 0x6}, {0x44?, 0x7f7151f96200?, 0x0?, 0xb7f1c8?})
squad-rest-api  | 	/go/pkg/mod/github.com/signintech/gopdf@v0.16.1/gopdf.go:1570 +0x7f4
squad-rest-api  | github.com/signintech/gopdf.(*GoPdf).AddTTFFontByReaderWithOption(0xc00018af00, {0xb3d4be, 0x6}, {0xc21fc0, 0xc000e28990}, {0xa8?, 0x1000041325a?, 0x0?, 0xb7f1c8?})
squad-rest-api  | 	/go/pkg/mod/github.com/signintech/gopdf@v0.16.1/gopdf.go:1527 +0x26b
squad-rest-api  | github.com/signintech/gopdf.(*GoPdf).AddTTFFontWithOption(0x280?, {0xb3d4be, 0x6}, {0xb4379b, 0x12}, {0x7?, 0x280?, 0x0?, 0xb7f1c8?})
squad-rest-api  | 	/go/pkg/mod/github.com/signintech/gopdf@v0.16.1/gopdf.go:1591 +0x177
squad-rest-api  | github.com/signintech/gopdf.(*GoPdf).AddTTFFont(0xaf9ea0?, {0xb3d4be?, 0x7f7151f96200?}, {0xb4379b?, 0x40d928?})
squad-rest-api  | 	/go/pkg/mod/github.com/signintech/gopdf@v0.16.1/gopdf.go:1596 +0x33
squad-rest-api  | main.PostContract({0xc29cb0, 0xc0001de000}, 0xc000e28840?)
```

Have you got any hints how to fix it?

Thanks,
Remus.

**Comment by oneplus1000** [comment]
```GO
pdf := gopdf.GoPdf{}

pdf.Start(gopdf.Config{ PageSize: *gopdf.PageSizeA4 })   <---- here

err := pdf.AddTTFFont("roboto", "roboto-regular.ttf")
if err != nil {
http.Error(w, "font not found", http.StatusInternalServerError)
  return
}
err = pdf.SetFont("roboto", "", 16)
if err != nil {
http.Error(w, "failed to set font", http.StatusInternalServerError)
  return
}

pdf.AddPage()
```
I think putting Start on top, might solve the problem.

**Comment by remusmp** [comment]
That solves it. Thank you!
