### ISSUE TITLE
panic en AddChars

### ISSUE THREAD

**Issue by weidongbcn** [signintech/gopdf#273]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1e8 pc=0x4ea943]

goroutine 1 [running]:
github.com/signintech/gopdf.(*SubsetFontObj).AddChars(0x0, {0x5244aa, 0xc})
        /home/debian/go/pkg/mod/github.com/signintech/gopdf@v0.19.0/subset_font_obj.go:139 +0xc3
github.com/signintech/gopdf.(*GoPdf).Cell(0xc000118000, 0x0?, {0x5244aa, 0xc})
        /home/debian/go/pkg/mod/github.com/signintech/gopdf@v0.19.0/gopdf.go:1093 +0xb3

**Comment by vantaboard** [comment]
@weidongbcn please provide an example so I can reproduce this.
